server:
  port: 0
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:cloud-bbdd
    driverClassName: org.h2.Driver
    username: cloud
    password: cloud
  jpa:
    hibernate:
     ddl-auto: validate